CREATE TABLE public."directories" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "parent_id" int4 NULL,
    "code" varchar NOT NULL,
    "real_name" varchar NOT NULL,
    "index" int4 NOT NULL,
    "dir_index" int4 NOT NULL,
    UNIQUE ("parent_id", "code"),
    UNIQUE ("parent_id", "index")
)
;

CREATE TABLE public."medias" (
    "id" int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "directory_id" int4 NOT NULL,
    "name" varchar NOT NULL,
    "real_name" varchar NOT NULL,
    "type" public."file_type" NOT NULL,
    "index" int4 NOT NULL,
    "dir_index" int4 NOT NULL,
    "size" int8 NOT NULL,
    "mime_type" varchar NOT NULL,
    "width" int4 NULL,
    "height" int4 NULL,
    "duration" int4 NULL,
    "fps" int4 NULL,
    "bitrate" int4 NULL,
    "codec" varchar NULL,
    "audio_codec" varchar NULL,
    "is_muted" bool NULL,
    "last_modified" timestamptz(0) NOT NULL,
    "with_preview" bool NOT NULL DEFAULT FALSE,
    "with_thumbnails" bool NOT NULL DEFAULT FALSE,
    "created_at" timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
)
;

ALTER TABLE public."directories" ADD FOREIGN KEY ("parent_id") REFERENCES public."directories" ("id");

ALTER TABLE public."medias" ADD FOREIGN KEY ("directory_id") REFERENCES public."directories" ("id");
